# ResourceClaimTemplate: Small Trainium2 (1 Neuron device, 1 logical NeuronCore)
# Use case: lightweight inference workloads on trn2.48xlarge
apiVersion: resource.k8s.io/v1beta1
kind: ResourceClaimTemplate
metadata:
  name: s-lnc1-trn2
spec:
  spec:
    devices:
      constraints:
      - matchAttribute: resource.aws.com/devicegroup1_id
        requests:
        - neurons
      requests:
      - allocationMode: ExactCount
        count: 1
        deviceClassName: neuron.aws.com
        name: neurons
        selectors:
        - cel:
            expression: device.attributes['neuron.aws.com'].instanceType == 'trn2.48xlarge'
      config:
      - requests: ["neurons"]
        opaque:
          driver: neuron.aws.com
          parameters:
            apiVersion: neuron.aws.com/v1
            kind: NeuronConfig
            logicalNeuronCore: 1
