apiVersion: v1
kind: Service
metadata:
  name: qwen-vllm-tp1
spec:
  selector:
    app: qwen-vllm-tp1
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-vllm-tp1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen-vllm-tp1
  template:
    metadata:
      labels:
        app: qwen-vllm-tp1
    spec:
      schedulerName: my-scheduler
      nodeSelector:
        karpenter.sh/nodepool: neuron-trn-2 
      containers:
        - name: app
          image: public.ecr.aws/neuron/pytorch-inference-vllm-neuronx:0.9.1-neuronx-py311-sdk2.26.1-ubuntu22.04
          #imagePullPolicy: Always
          command:
            - /bin/bash
            - "-exc"
            - |
              set -x
              vllm serve $MODEL_ID \
                --tensor-parallel-size 1 \
                --max-num-seqs 1  \
                --max-model-len 128 \
                --override-neuron-config '{"save_sharded_checkpoint": true}' 
              #while true; do sleep 3600; done
          resources:
            requests:
              aws.amazon.com/neuroncore: 1
              cpu: 4
            limits:
              aws.amazon.com/neuroncore: 1
              cpu: 4
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: adhoc-python-packages-deb-pvc
              mountPath: /var/mdl
          env:
            - name: VLLM_NEURON_FRAMEWORK
              value: "neuronx-distributed-inference"
            - name: NEURON_COMPILED_ARTIFACTS
              value: "/var/mdl/Qwen-06B-BS1-SL128-TP1"
            - name: MODEL_ID
              value: "/var/mdl/Qwen-06B-BS1-SL128-TP1"
          ports:
            - containerPort: 8000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 50
            failureThreshold: 170
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 128Gi
        - name: adhoc-python-packages-deb-pvc
          persistentVolumeClaim:
            claimName: adhoc-python-packages-deb-pvc
