apiVersion: v1
kind: Service
metadata:
  name: qwen-vllm
spec:
  selector:
    app: qwen-vllm
  ports:
    - port: 8000
      targetPort: 8000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qwen-vllm
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qwen-vllm
  template:
    metadata:
      labels:
        app: qwen-vllm
    spec:
      resourceClaims:
      - name: xl-trn2
        resourceClaimTemplateName: xl-trn2
      containers:
        - name: app
          image: public.ecr.aws/neuron/pytorch-inference-vllm-neuronx:0.9.1-neuronx-py311-sdk2.26.1-ubuntu22.04
          command:
            - /bin/bash
            - "-exc"
            - |
              set -x
              vllm serve $MODEL_ID \
                --tensor-parallel-size 32 \
                --max-num-seqs 4  \
                --max-model-len 1024  
              #while true; do sleep 3600; done
          resources:
            claims:
            - name: xl-trn2
            requests:
              cpu: 90
            limits:
              cpu: 90
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: 621547421844-ap-southeast-4-pvc
              mountPath: /var/mdl
          env:
            - name: VLLM_NEURON_FRAMEWORK
              value: "neuronx-distributed-inference"
            - name: NEURON_COMPILED_ARTIFACTS
              value: "/var/mdl/Qwen-32B-BS4-SL1k-TP32"
            - name: MODEL_ID
              value: "Qwen/Qwen3-32B"
          ports:
            - containerPort: 8000
              protocol: TCP
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 30
            timeoutSeconds: 50
            failureThreshold: 570
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 60
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 128Gi
        - name: 621547421844-ap-southeast-4-pvc
          persistentVolumeClaim:
            claimName: 621547421844-ap-southeast-4-pvc
