apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: amd-neuron-trn1
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["trn1"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: amd-neuron-al2023
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 10m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: amd-neuron-al2023
spec:
  amiSelectorTerms:
    - alias: "al2023@v20250501"
  role: "KarpenterNodeRole-cova-use1"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "cova-use1"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "cova-use1" 
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 900Gi
        volumeType: gp3
        encrypted: true
