apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: amd-neuron-trn1
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.k8s.aws/instance-family
          operator: In
          values: ["trn1"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: amd-neuron
      expireAfter: 720h # 30 * 24h = 720h
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 10m
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: amd-neuron
spec:
  amiFamily: AL2 # Amazon Linux 2
  amiSelectorTerms:
    - id: "ami-0e73cfd34ee52b6a6"
    - id: "ami-077b8064c2a1a3186"
    - id: "ami-057dddc807f3f6644"
  role: "KarpenterNodeRole-flux-usw2"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "flux-usw2"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "flux-usw2" 
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 900Gi
        volumeType: gp3
        encrypted: true
