apiVersion: batch/v1
kind: Job
metadata:
  name: compile
spec:
  template:
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        karpenter.sh/nodepool: amd-neuron-trn1
      #serviceAccountName: appsimulator
      schedulerName: my-scheduler
      containers:
      - name: app
        image: 920372998901.dkr.ecr.us-east-1.amazonaws.com/model:amd64-neuron
        imagePullPolicy: Always
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          - name: neuron-bits-use1-pvc
            mountPath: /model
        command: 
        - /bin/bash
        - "-exc"
        - |
          set -x
          python /download_hf_model.py 
          find /model -type f -name '*.deb' -exec sh -c '
            for pkg; do
              cp "$pkg" / &&
              apt install -y "/$(basename "$pkg")"
            done
          ' _ {} +
          find /model -type f -name '*.whl' -exec sh -c '
            for pkg; do
              cp "$pkg" / &&
              pip install "/$(basename "$pkg")"
            done
          ' _ {} +
          while true; do sleep 3600; done
        resources:
          limits:
            aws.amazon.com/neuron: 16
          requests: 
            aws.amazon.com/neuron: 16
        env:
        - name: NODEPOOL
          value: "amd-neuron-trn1"
        - name: COMPILER_WORKDIR_ROOT
          value: "/model"
        - name: HEIGHT
          value: "512"
        - name: WIDTH
          value: "512"
        - name: MAX_SEQ_LEN
          value: "32"
        - name: GUIDANCE_SCALE
          value: "3.5"
        - name: MODEL_ID
          value: "black-forest-labs/FLUX.1-dev"
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secrets
              key: HUGGINGFACE_TOKEN
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: neuron-bits-use1-pvc
          persistentVolumeClaim:
            claimName: neuron-bits-use1-pvc
