apiVersion: batch/v1
kind: Job
metadata:
  name: compile-512x512
spec:
  template:
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        karpenter.sh/nodepool: amd-neuron-trn1
      #serviceAccountName: appsimulator
      schedulerName: my-scheduler
      containers:
      - name: app
        #image: 891377065549.dkr.ecr.us-west-2.amazonaws.com/model:amd64-neuron
        image: 920372998901.dkr.ecr.us-east-1.amazonaws.com/model:amd64-neuron
        imagePullPolicy: Always
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          - name: s3-flux-pvc
            mountPath: /model
        command: 
        - /bin/bash
        - "-exc"
        - |
          set -x
          #mkdir -p /model/512x512
          #cd /src
          #./compile.sh 
          #cp -r * /model/512x512
          #python /benchmark-flux.py 
          while true; do sleep 3600; done
        resources:
          limits:
            aws.amazon.com/neuron: 16
          requests: 
            aws.amazon.com/neuron: 16
        env:
        - name: NODEPOOL
          value: "amd-neuron-trn1"
        - name: COMPILER_WORKDIR_ROOT
          value: "/model/512x512"
        - name: HEIGHT
          value: "512"
        - name: WIDTH
          value: "512"
        - name: MAX_SEQ_LEN
          value: "32"
        - name: GUIDANCE_SCALE
          value: "3.5"
        - name: MODEL_ID
          value: "black-forest-labs/FLUX.1-dev"
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secrets
              key: HUGGINGFACE_TOKEN
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: s3-flux-pvc
          persistentVolumeClaim:
            claimName: s3-flux-pvc
