apiVersion: batch/v1
kind: Job
metadata:
  name: compile-256x256
spec:
  template:
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        karpenter.sh/nodepool: amd-neuron-trn1
      serviceAccountName: appsimulator
      schedulerName: my-scheduler
      containers:
      - name: app
        image: 891377065549.dkr.ecr.us-west-2.amazonaws.com/model:amd64-neuron
        #image: 920372998901.dkr.ecr.us-west-2.amazonaws.com/model:amd64-neuron
        imagePullPolicy: Always
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          #- name: s3-flux-pvc
          #  mountPath: /model
        command: 
        - /bin/bash
        - "-exc"
        - |
          set -x
          while true; do sleep 3600; done
          mkdir -p /model/256x256
          cd /src
          ./compile.sh 
          cp -r * /model/256x256
          python /benchmark-flux.py 
        resources:
          limits:
            aws.amazon.com/neuron: 8
          requests: 
            aws.amazon.com/neuron: 8
        env:
        - name: NODEPOOL
          value: "amd-neuron-trn1"
        - name: COMPILER_WORKDIR_ROOT
          value: "/model/256x256"
        - name: HEIGHT
          value: "256"
        - name: WIDTH
          value: "256"
        - name: MAX_SEQ_LEN
          value: "32"
        - name: GUIDANCE_SCALE
          value: "3.5"
        - name: MODEL_ID
          value: "black-forest-labs/FLUX.1-dev"
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secrets
              key: HUGGINGFACE_TOKEN
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        #- name: s3-flux-pvc
        #  persistentVolumeClaim:
        #    claimName: s3-flux-pvc
