apiVersion: v1
kind: ConfigMap
metadata:
  name: cova-gradio-config
data:
  models.json: |
    [
    	{
          "name": "512 × 512",
          "host_env": "FLUX_NEURON_512X512_MODEL_API_SERVICE_HOST",
          "port_env": "FLUX_NEURON_512X512_MODEL_API_SERVICE_PORT",
          "height": 512,
          "width": 512,
          "caption_host_env": "MLLAMA_32_11B_VLLM_TRN1_SERVICE_HOST",
          "caption_port_env": "MLLAMA_32_11B_VLLM_TRN1_SERVICE_PORT",
          "caption_max_new_tokens": 1024
        }
    ]
