apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-flux-pv
spec:
  capacity:
    storage: 1200Gi 
  accessModes:
    - ReadWriteMany 
  storageClassName: "" 
  claimRef: 
    namespace: default 
    name: s3-flux-pvc 
  mountOptions:
    - region=us-west-2
  csi:
    driver: s3.csi.aws.com 
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: flux1-dev-neuron
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-flux-pvc
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi 
  volumeName: s3-flux-pv 
