---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mllama-32-11b-vllm-trn1-config
data:
  vllm_config.yaml: |
    model: "yahavb/Llama-3.2-11B-Vision-Instruct-neuron-checkpoint"
    tensor_parallel_size: 32
    max_num_seqs: 1
    block_size: 4096
    max_model_len: 128000
    override_neuron_config:
      skip_warmup: true
      context_encoding_buckets: [1024, 16384]
      token_generation_buckets: [1024, 16384]
      sequence_parallel_enabled: False
      is_continuous_batching: True
      on_device_sampling_config: 
        global_topk: 64
        dynamic: True
        deterministic: False
    device: "neuron"
---
