apiVersion: v1
kind: PersistentVolume
metadata:
  name: neuron-bits-use1-pv
spec:
  capacity:
    storage: 1200Gi 
  accessModes:
    - ReadWriteMany 
  storageClassName: "" 
  claimRef: 
    namespace: default 
    name: neuron-bits-use1-pvc 
  mountOptions:
    - region=us-east-1
  csi:
    driver: s3.csi.aws.com 
    volumeHandle: s3-csi-driver-volume
    volumeAttributes:
      bucketName: neuron-bits-use1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neuron-bits-use1-pvc
spec:
  accessModes:
    - ReadWriteMany # Supported options: ReadWriteMany / ReadOnlyMany
  storageClassName: "" # Required for static provisioning
  resources:
    requests:
      storage: 1200Gi 
  volumeName: neuron-bits-use1-pv 
