# ----------------------------------------------------------------------------
# RayJob: 2-llama3-finetune-trn1-rayjob-create-data
#
# Description:
# This RayJob is responsible for generating fine-tuning test data required for
# the Llama3.1 8B model training. It sources data from the specified dataset, processes
# it, and prepares it for use in subsequent training stages. The job runs a Python
# script (`download_llama.py`) that performs these data preparation steps.

# Usage:
# Apply this configuration to your Kubernetes cluster using `kubectl apply -f 2-llama3-finetune-trn1-rayjob-create-data.yaml`.
# Ensure that the Ray cluster (`kuberay-trn1`) is running and accessible in the specified namespace.
# ----------------------------------------------------------------------------

apiVersion: ray.io/v1
kind: RayJob
metadata:
  name: trn1-rayjob-create-data
spec:
  submissionMode: K8sJobMode
  entrypoint: "bash download_llama_and_dolly.sh"
  entrypointNumCpus: 1
  runtimeEnvYAML: |
    working_dir: /llama3_finetune
    env_vars:
      PYTHONUNBUFFERED: '0'
  clusterSelector:
    ray.io/cluster: kuberay-trn1
  submitterPodTemplate:
    spec:
      # Add the nodeSelector field here in the Pod spec
      nodeSelector:
        # Key-value pair matching the label on your target node(s)
        node.kubernetes.io/instance-type: trn1.32xlarge
      containers:
      - name: ray-job-submitter
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/kuberay_trn1_llama3.1_pytorch2:latest
      restartPolicy: Never
      tolerations:
        - key: "aws.amazon.com/neuron"
          operator: "Exists"
          effect: "NoSchedule"
